//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual Courses Courses { get; set; }
        public virtual Users Users { get; set; }
    }
}
